In [12]:
import numpy as np
import pandas as pd

In [19]:
a=pd.read_csv("/content/sample_data/customer_churn.csv")
a

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [39]:
import numpy as np

In [38]:
import pandas as pd

In [41]:
File = pd.read_csv("/content/sample_data/cars.csv")

In [42]:
File

      mpg  cylinders cubicinches   hp weightlbs  time-to-60  year     brand
0    14.0          8         350  165      4209          12  1972       US.
1    31.9          4          89   71      1925          14  1980   Europe.
2    17.0          8         302  140      3449          11  1971       US.
3    15.0          8         400  150      3761          10  1971       US.
4    30.5          4          98   63      2051          17  1978       US.
..    ...        ...         ...  ...       ...         ...   ...       ...
256  17.0          8         305  130      3840          15  1980       US.
257  36.1          4          91   60      1800          16  1979    Japan.
258  22.0          6         232  112      2835          15  1983       US.
259  18.0          6         232  100      3288          16  1972       US.
260  22.0          6         250  105      3353          15  1977       US.

[261 rows x 8 columns]